# Generated by Django 5.0.1 on 2024-02-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210126_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='do_list',
            old_name='check',
            new_name='check_list',
        ),
    ]
